app:
  kind: development
  port: 8081

db:
  mongo:
    username: root
    password: root
    host: 127.0.0.1
    port: 27017
    name: carrier_development
    auth: admin
    collection: carrier_account
