app:
    base_url: http://localhost:8081
    domain: localhost
    kind: staging
    port: 8081

jwt:
    confirm_email:
        secret:
            jwt_secret: logpostemailconfirm
        options:
            expires_in: 10m
            issuer: logpost
            audience: mailer
    private_route:
        secret:
            jwt_secret: logpostprivateroute
        options:
            expires_in: 10m
            issuer: logpost
            audience: logpost

db:
    required:
        isAuth: true
    mongo:
        protocal: mongodb+srv
        username: logpost
        password: logpost
        host: cluster0.j9jsp.mongodb.net
        database: logpost-stag
        options: ?retryWrites=true&w=majority
        collection: carrier_account
